<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<!-- Không tạo file .pdb -->
		<GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
		<!-- Không tạo .deps.json -->
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Resource\Fonts\Fira_Sans\FiraSans-Bold.ttf" />
	  <None Remove="Resource\Fonts\Fira_Sans\FiraSans-Regular.ttf" />
	  <None Remove="Resource\logo_40.png" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Resource\logo_40.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Resource\Fonts\Fira_Sans\FiraSans-Bold.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Resource\Fonts\Fira_Sans\FiraSans-Regular.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
</Project>
