name: AutoVersionBump

on:
  # schedule:
  #   - cron: '0 11 * * 5'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch for version up'
        required: true
      type:
        description: 'Version type: patch, build, minor, major'
        required: false
        default: 'patch'

jobs:
  version_bump:
    runs-on: windows-latest
    env:
     ISLOCAL: false
     BUILD_PERMISSION_JSON: ${{ vars.BUILD_PERMISSION_JSON }}
     GITHUB_TOKEN: ${{ secrets.WORK_FLOW_ACCESS_TOKEN }}
     TARGET_BRANCH: ${{ github.event.inputs.branch || 'dev' }}
     TARGET_MODULE: ArtWiz
     TRIGGER_ACTOR: ${{ github.triggering_actor }}
     VERSION_UP_ISSUE_ID: "#52"
     EXCLUDE_ISSUE_ID: "12,52"
     AUTO_DECIDE_VERSION_UP: true
     REPO_OWNER: ${{ github.repository_owner }}
     REPO_NAME: ArtWiz  # Github event ko có giá trị này :((
     TARGET_RELEASED_BRANCH: ${{ github.event.inputs.branch || 'dev' }}
     VERSION_UP_TYPE: ${{ github.event.inputs.type || 'patch' }}
     CS_VERSION_UP_FILE_PATH: SPRNetTool\ArtWiz.csproj
    steps:
      - name: verify build permission
        shell: powershell
        run: |
            $Headers = @{
                Authorization = "token ${{ env.GITHUB_TOKEN }}"
            }
            $Uri = "https://raw.githubusercontent.com/TrdHuy/_TrdBuildPlugin/master/DotNet/BuildPermissionCheckHelper.ps1"
            Invoke-RestMethod -Uri $Uri -Headers $Headers -OutFile BuildPermissionCheckHelper.ps1
            & .\BuildPermissionCheckHelper.ps1
      - name: Setup ENV
        shell: powershell
        run: |
            $Headers = @{
                    Authorization = "token ${{ env.GITHUB_TOKEN }}"
            }
            $Uri = "https://raw.githubusercontent.com/TrdHuy/_TrdBuildPlugin/master/DotNet/UpdateVersionForDotnetPlatform.ps1"
            Invoke-RestMethod -Uri $Uri -Headers $Headers -OutFile UpdateVersionForDotnetPlatform.ps1
            & .\UpdateVersionForDotnetPlatform.ps1
