name: AutoVersionBump

on:
  workflow_dispatch:  # Đây là sự kiện để kích hoạt quy trình
    inputs:
      my_input:
        description: A custom input
        required: false
        default: "default_value"

jobs:
  version_bump:
    runs-on: ubuntu-latest
    env:
     BRANCH_NAME: refs/heads/dev
    steps:
    - name: Print Input
      run: |
        echo "Input: ${{ github.event.inputs.my_input }}"
        
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}

    - name: Githublog
      id: extract_version
      uses: actions/github-script@v5
      with:
        script: |
          const log = ${{ toJSON(github) }};
          console.log(log);
    - name: Github object
      uses: actions/github-script@v5
      with:
        script: |
          console.log(github);    
          
    - name: project file detail
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const path = 'SPRNetTool/SPRNetTool.csproj';  // Thay đổi đường dẫn tương ứng
          const versionRegex = /<Version>(.*?)<\/Version>/;
          // Đọc nội dung của tệp .csproj
          let csprojContent = fs.readFileSync(path, 'utf8');
          console.log(csprojContent);
          
    - name: Build
      run: |
          echo "Building the code..."
          
    - name: Get last commit message
      id: last_commit
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(context.repo)
          const data = await github.repos.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: '${{ env.BRANCH_NAME }}',
            per_page: 1
          });
          console.log(data)
          
