name: AutoVersionBump

on:
  push:
    branches:
      - '*'

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
    - name: Print Input
      run: |
        echo "Input: ${{ github.event.inputs.my_input }}"
        
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Githublog
      id: extract_version
      uses: actions/github-script@v5
      with:
        script: |
          const log = ${{ toJSON(github) }};
          console.log(log);
    - name: Github object
      uses: actions/github-script@v5
      with:
        script: |
          console.log(github);    
          
    - name: project file detail
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const path = 'SPRNetTool/SPRNetTool.csproj';  // Thay đổi đường dẫn tương ứng
          const versionRegex = /<Version>(.*?)<\/Version>/;
          // Đọc nội dung của tệp .csproj
          let csprojContent = fs.readFileSync(path, 'utf8');
          console.log(csprojContent);
          
