name: Handle Edited Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize  # Thêm loại sự kiện synchronize

jobs:
  handle-edited-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Get Pull Request Message
      id: pull-request-message
      run: |
        echo "Pull Request Message: ${{ github.event.pull_request.body }}"

    - name: Use Pull Request Message
      run: |
        message="${{ steps.pull-request-message.outputs.pull_request_message }}"
        # Bây giờ bạn có thể sử dụng biến "message" để làm gì đó với nội dung của pull request message.
