name: Auto Version Bump

on:
  push:
    branches:
      - '*'

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Extract Version Number from Commit
      id: extract_version
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const path = 'SPRNetTool/SPRNetTool.csproj';  // Thay đổi đường dẫn tương ứng
          const versionRegex = /<Version>(.*?)<\/Version>/;
          // Đọc nội dung của tệp .csproj
          let csprojContent = fs.readFileSync(path, 'utf8');
          console.log(csprojContent);
          
