name: Auto Version Bump

on:
  push:
    branches:
      - '*'

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Extract Version Number from Commit
      id: extract_version
      uses: actions/github-script@v5
      with:
        script: |
          const log = ${{ toJSON(github) }};
          console.log(log);
